import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import Sidebar from "@/components/sidebar";
import React from "react";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={poppins.variable}>
      <body>
        <Sidebar />
        <main>{children}</main>
      </body>
    </html>
  );
}
